---
title: ""
format: pdf
---

\begin{table}[!htbp] \centering 
  \caption{} 
  \label{} 
\small 
\begin{tabular}{@{\extracolsep{-11pt}}lD{.}{.}{-2} D{.}{.}{-2} D{.}{.}{-2} D{.}{.}{-2} D{.}{.}{-2} D{.}{.}{-2} } 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & \multicolumn{6}{c}{Dependent variable} \\ 
\cline{2-7} 
\\[-1.8ex] & \multicolumn{6}{c}{BToxicNum01} \\ 
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)} & \multicolumn{1}{c}{(5)} & \multicolumn{1}{c}{(6)}\\ 
\hline \\[-1.8ex] 
 PolIdComp2Sd &  & -0.06^{***} & -0.06^{***} & -0.06^{***} & -0.06^{***} & -0.06^{***} \\ 
  &  & (0.005) & (0.01) & (0.01) & (0.005) & (0.01) \\ 
  Age2Sd &  &  & -0.03^{***} & -0.03^{***} &  & -0.03^{***} \\ 
  &  &  & (0.01) & (0.01) &  & (0.01) \\ 
  GenderOther &  &  & -0.01 & -0.01 &  & -0.01 \\ 
  &  &  & (0.02) & (0.02) &  & (0.02) \\ 
  GenderWoman &  &  & 0.001 & 0.0001 &  & -0.0000 \\ 
  &  &  & (0.01) & (0.01) &  & (0.01) \\ 
  EducationNum2Sd &  &  & 0.02^{***} & 0.02^{***} &  & 0.02^{***} \\ 
  &  &  & (0.01) & (0.01) &  & (0.01) \\ 
  MaritalStatusMarried &  &  & 0.0002 & -0.0001 &  & -0.0000 \\ 
  &  &  & (0.01) & (0.01) &  & (0.01) \\ 
  MaritalStatusNever married &  &  & 0.002 & 0.002 &  & 0.002 \\ 
  &  &  & (0.01) & (0.01) &  & (0.01) \\ 
  MaritalStatusPrefer not to answer &  &  & -0.01 & -0.01 &  & -0.01 \\ 
  &  &  & (0.02) & (0.02) &  & (0.02) \\ 
  MaritalStatusSeparated &  &  & 0.04 & 0.04 &  & 0.04 \\ 
  &  &  & (0.02) & (0.02) &  & (0.02) \\ 
  MaritalStatusWidowed &  &  & -0.01 & -0.01 &  & -0.01 \\ 
  &  &  & (0.02) & (0.02) &  & (0.02) \\ 
  ReligionEvangelical Protestant &  &  & -0.01 & -0.01 &  & -0.01 \\ 
  &  &  & (0.01) & (0.01) &  & (0.01) \\ 
  ReligionJewish &  &  & -0.02 & -0.02 &  & -0.02 \\ 
  &  &  & (0.02) & (0.02) &  & (0.02) \\ 
  ReligionMainline Protestant &  &  & -0.02^{**} & -0.02^{**} &  & -0.02^{**} \\ 
  &  &  & (0.01) & (0.01) &  & (0.01) \\ 
  ReligionMormon &  &  & -0.02 & -0.02 &  & -0.02 \\ 
  &  &  & (0.03) & (0.03) &  & (0.03) \\ 
  ReligionMuslim &  &  & 0.03 & 0.03 &  & 0.02 \\ 
  &  &  & (0.02) & (0.02) &  & (0.02) \\ 
  ReligionNot available &  &  & -0.01 & -0.01 &  & -0.01 \\ 
  &  &  & (0.01) & (0.01) &  & (0.01) \\ 
  ReligionNot religious &  &  & -0.01 & -0.01 &  & -0.01 \\ 
  &  &  & (0.01) & (0.01) &  & (0.01) \\ 
  ReligionOther Religion &  &  & 0.001 & -0.0002 &  & -0.0003 \\ 
  &  &  & (0.01) & (0.01) &  & (0.01) \\ 
  SexualOrientationGay or lesbian &  &  & -0.001 & -0.001 &  & -0.0004 \\ 
  &  &  & (0.01) & (0.01) &  & (0.01) \\ 
  SexualOrientationHeterosexual / straight &  &  & -0.01 & -0.01 &  & -0.01 \\ 
  &  &  & (0.01) & (0.01) &  & (0.01) \\ 
  SexualOrientationOther &  &  & 0.02 & 0.02 &  & 0.02 \\ 
  &  &  & (0.02) & (0.02) &  & (0.02) \\ 
  HhSizeHh2 &  &  & 0.004 & 0.004 &  & 0.004 \\ 
  &  &  & (0.01) & (0.01) &  & (0.01) \\ 
  HhSizeHh3 &  &  & 0.01 & 0.01 &  & 0.01 \\ 
  &  &  & (0.01) & (0.01) &  & (0.01) \\ 
  HhSizeHh4 &  &  & 0.01 & 0.01 &  & 0.01 \\ 
  &  &  & (0.01) & (0.01) &  & (0.01) \\ 
  HhSizeHh5 &  &  & 0.002 & 0.003 &  & 0.003 \\ 
  &  &  & (0.01) & (0.01) &  & (0.01) \\ 
  HhSizeHh6 or more &  &  & 0.01 & 0.01 &  & 0.01 \\ 
  &  &  & (0.01) & (0.01) &  & (0.01) \\ 
  HhSizeHhOther &  &  & 0.003 & 0.004 &  & 0.005 \\ 
  &  &  & (0.02) & (0.02) &  & (0.02) \\ 
  RegionNortheast &  &  & -0.01^{*} & -0.01^{*} &  & -0.01^{*} \\ 
  &  &  & (0.01) & (0.01) &  & (0.01) \\ 
  RegionSouth &  &  & -0.004 & -0.004 &  & -0.004 \\ 
  &  &  & (0.01) & (0.01) &  & (0.01) \\ 
  RegionWest &  &  & -0.003 & -0.003 &  & -0.003 \\ 
  &  &  & (0.01) & (0.01) &  & (0.01) \\ 
  Income2Sd &  &  & -0.01 & -0.01 &  & -0.01 \\ 
  &  &  & (0.01) & (0.01) &  & (0.01) \\ 
  RaceBlack &  &  & 0.01 & 0.01 &  & 0.01 \\ 
  &  &  & (0.01) & (0.01) &  & (0.01) \\ 
  RaceHispanic &  &  & 0.03^{**} & 0.03^{**} &  & 0.03^{**} \\ 
  &  &  & (0.01) & (0.01) &  & (0.01) \\ 
  RaceOther &  &  & -0.01 & -0.01 &  & -0.01 \\ 
  &  &  & (0.03) & (0.03) &  & (0.02) \\ 
  RaceWhite &  &  & 0.02^{**} & 0.02^{**} &  & 0.02^{**} \\ 
  &  &  & (0.01) & (0.01) &  & (0.01) \\ 
  Order &  &  & -0.01^{***} & -0.01^{***} &  & -0.01^{***} \\ 
  &  &  & (0.001) & (0.001) &  & (0.001) \\ 
  anticonservative &  &  &  & 0.10^{***} &  & 0.10^{***} \\ 
  &  &  &  & (0.01) &  & (0.01) \\ 
  america &  &  &  & 0.02^{***} &  & 0.02^{**} \\ 
  &  &  &  & (0.01) &  & (0.01) \\ 
  christianity &  &  &  & -0.04 &  & -0.04 \\ 
  &  &  &  & (0.02) &  & (0.02) \\ 
  suggestive &  &  &  & 0.18^{***} &  & 0.18^{***} \\ 
  &  &  &  & (0.01) &  & (0.01) \\ 
  drugs &  &  &  & -0.06^{***} &  & -0.06^{***} \\ 
  &  &  &  & (0.01) &  & (0.01) \\ 
  ideo\_commenterB &  &  &  & 0.07^{***} &  & 0.07^{***} \\ 
  &  &  &  & (0.005) &  & (0.005) \\ 
  target\_likes\_count &  &  &  & -0.0003^{**} &  & -0.0003^{**} \\ 
  &  &  &  & (0.0001) &  & (0.0001) \\ 
  Constant & -0.0000 & 0.0000 & -0.01 & -0.08^{***} & -0.0001 & -0.08^{***} \\ 
  & (0.003) & (0.003) & (0.02) & (0.02) & (0.003) & (0.02) \\ 
 \hline \\[-1.8ex] 
Observations & \multicolumn{1}{c}{32,695} & \multicolumn{1}{c}{32,695} & \multicolumn{1}{c}{32,695} & \multicolumn{1}{c}{32,695} & \multicolumn{1}{c}{32,695} & \multicolumn{1}{c}{32,695} \\ 
Log Likelihood & \multicolumn{1}{c}{-11,041.93} & \multicolumn{1}{c}{-10,956.70} & \multicolumn{1}{c}{-10,774.14} & \multicolumn{1}{c}{-10,137.60} & \multicolumn{1}{c}{-10,916.51} & \multicolumn{1}{c}{-10,113.87} \\ 
Akaike Inf. Crit. & \multicolumn{1}{c}{22,091.85} & \multicolumn{1}{c}{21,923.40} & \multicolumn{1}{c}{21,628.28} & \multicolumn{1}{c}{20,369.19} & \multicolumn{1}{c}{21,847.03} & \multicolumn{1}{c}{20,327.75} \\ 
Bayesian Inf. Crit. & \multicolumn{1}{c}{22,125.43} & \multicolumn{1}{c}{21,965.38} & \multicolumn{1}{c}{21,964.08} & \multicolumn{1}{c}{20,763.76} & \multicolumn{1}{c}{21,905.79} & \multicolumn{1}{c}{20,747.50} \\ 
\hline 
\hline \\[-1.8ex] 
\textit{Note:}  & \multicolumn{6}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\ 
\end{tabular} 
\end{table} 
